{% set name = "conda-recipe-manager" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../

build:
  number: 0
  noarch: python
  script: pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - convert = conda_recipe_manager.commands.convert:convert

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.11
    - click >=8.1.7
    - conda
    - jinja2
    - pyyaml
    - jsonschema

test:
  imports:
    - conda_recipe_manager.parser
    - conda_recipe_manager.commands
  source_files:
    - tests/
  requires:
    - pip
    - pytest
    - pytest-xdist
  commands:
    - pip check
    - python -m pytest -n auto tests/

about:
  home: https://github.com/anaconda/conda-recipe-manager
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Helper tool for recipes on aggregate.
  description: |
    Renders local recipes, provides build orders, find outdated recipes.
  doc_url: https://github.com/anaconda/conda-recipe-manager
  dev_url: https://github.com/anaconda/conda-recipe-manager
