{% set name = "conda-recipe-manager" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../

build:
  number: 0
  noarch: python
  script: pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - conda-recipe-manager = conda_recipe_manager.commands.conda_recipe_manager:conda_recipe_manager
    - crm = conda_recipe_manager.commands.conda_recipe_manager:conda_recipe_manager

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.11
    - click >=8.1.7
    - conda
    - jinja2
    - pyyaml
    - jsonschema
    - requests
    - gitpython
    - networkx
    - matplotlib
    - pygraphviz

test:
  imports:
    - conda_recipe_manager.commands
    - conda_recipe_manager.licenses
    - conda_recipe_manager.parser
  source_files:
    - tests/
  requires:
    - pip
    - pytest
    - pytest-xdist
    - pytest-socket
    - pyfakefs
  commands:
    - pip check
    - python -m pytest -n auto --ignore=tests/test_aux_files tests/

about:
  home: https://github.com/anaconda/conda-recipe-manager
  license: BSD-3-Clause
  license_file: LICENSE
  license_url: https://github.com/anaconda/conda-recipe-manager/blob/main/LICENSE
  summary: Helper tool for recipes on aggregate.
  description: |
    Renders local recipes, provides build orders, find outdated recipes.
  doc_url: https://conda-incubator.github.io/conda-recipe-manager/index.html
  dev_url: https://github.com/anaconda/conda-recipe-manager
